spring:
  application:
    name: team4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_PATH}
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC # path, query, body, response ? ??
    tags-sorter: alpha # ??? ??? ??? ??
    operations-sorter: method # delete - get - patch - post - put ??? ??
  use-fqn: true